### ISSUE TITLE
CRUD Karyawan [Web]

### ISSUE THREAD

**Issue by irsyadulibad** [four-lab/apsensi-web#1]

**Comment by irsyadulibad** [comment]
Solved at #2

**Comment by irsyadulibad** [comment]
Silahkan Direview @DvdArdiansyahhh

**Comment by DvdArdiansyahhh** [comment]
## List Bug

- [x] Popup modal menyatu dengan header
- [ ] Tidak ada pesan validasi untuk menggunakan angka pada NIK
- [x] Maksimal nik
- [x] Nama lengkap bisa menggunakan angka & simbol
- [x] Tempat lahir bisa menggunakan angka & simbol
- [x] Username bisa menggunakan karakter selain "_" dan "."
- [ ] Jenis kelamin pakai bhs inggris


## Improvement

- [x] Kolom Password ditambahkan hint "Kosongkan bila tidak diubah"
- [ ] Password ditambahkan validasi untuk minimal & kombinasi

**Comment by DvdArdiansyahhh** [comment]
![Image](https://github.com/four-lab/apsensi-web/assets/124945304/50650e88-3f2b-44e9-800e-1136d5376d25)
