### ISSUE TITLE
Jadwal Pelajaran [Web]

### ISSUE THREAD

**Issue by irsyadulibad** [four-lab/apsensi-web#12]

**Comment by irsyadulibad** [comment]
Done at #13

**Comment by DvdArdiansyahhh** [comment]
## List Bug

- [x] Tombol "Atur Jadwal" tidak berfungsi [404 | Not Found]
- [x] Data yg tampil pada "Jadwal Pelajaran" tidak sama dengan data yg ditambahkan
- [x] Muncul Popup "Jadwal telah ada pada jam tersebut" pada kondisi
- "Jam Mulai = 08:30, Jam Akhir 09:30" (Data Pertama)
- "Jam Mulai = 09:30, Jam Akhir 10:30" (Data Kedua) <- Tdk bisa ditambahkan
- [x] Perubahan jadwal tidak masuk ketika:
- Menambahkan jadwal kelas pada suatu kelas
- Beralih ke kelas lain
- Beralih ke kelas yg tadi sudah ditambahkan jadwalnya
- Note: Tetapi data akan diperbarui ketika sudah refresh

## Improvement

- [ ] Jadwal hanya berisi jam dan menit saja, tdk menggunakan detik

**Comment by irsyadulibad** [comment]
> ## List Bug
> * [x]  Tombol "Atur Jadwal" tidak berfungsi [404 | Not Found]
> * [x]  Data yg tampil pada "Jadwal Pelajaran" tidak sama dengan data yg ditambahkan
> * [x]  Muncul Popup "Jadwal telah ada pada jam tersebut" pada kondisi
> * "Jam Mulai = 08:30, Jam Akhir 09:30" (Data Pertama)
> * "Jam Mulai = 09:30, Jam Akhir 10:30" (Data Kedua) <- Tdk bisa ditambahkan

Test lagi bang
