### ISSUE TITLE
CRUD Mapel [Web]

### ISSUE THREAD

**Issue by irsyadulibad** [four-lab/apsensi-web#6]

**Comment by irsyadulibad** [comment]
Done at #8

**Comment by muhyi7** [comment]
Silahkan direview @DvdArdiansyahhh

**Comment by DvdArdiansyahhh** [comment]
## List Bug

- [x] Popup modal menyatu dengan header
- [ ] Nama attribut **Nama Mapel** sama dengan **"Nama Kelas"** (name)
