### ISSUE TITLE
Manajemen Hari Libur

### ISSUE THREAD

**Issue by irsyadulibad** [four-lab/apsensi-web#7]

**Comment by irsyadulibad** [comment]
Done at #11

**Comment by irsyadulibad** [comment]
Mangga direview @DvdArdiansyahhh

**Comment by DvdArdiansyahhh** [comment]
## List Bug

- [ ] Informasi hari libur bisa memakai karakter simbol
- [ ] Tdk bisa hapus hari libur setelah menambahkan yg baru (404 | Not Found), kecuali di-refresh dulu
- [x] Popup yakin hapus muncul di belakang modal schedule saat mau menghapus

**Comment by DvdArdiansyahhh** [comment]
Done direview bang 👍

**Comment by DvdArdiansyahhh** [comment]
> Mangga direview [@DvdArdiansyahhh](https://github.com/DvdArdiansyahhh)

Done bang 👍
